[package]
name = "greenviper126/vluxysf"

description = """
Sound fetching system with a focus on simplicity! 

Source: https://github.com/Vlux-Entertainment/VluxySF
"""
version = "1.0.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["lib", "default.project.json", "LICENSE"]

exclude = [
    "docs",
    "build",
    "Tests",
    "CLAUDE.md",
    "aftman.toml",
    "moonwave.toml",
    "selene.toml",
    "stylua.toml",
    "sourcemap.json",
    "test-place.project.json",
]

[server-dependencies]

#main:

#optional:

[dev-dependencies]

#main:

#optional:


[dependencies]

#main:

#optional:
